pypdns/__init__.py,sha256=kHJO-HGrEfLJPc4o1n4WGIYhO9_vanYNpDuQLzw2Ctg,1105
pypdns/api.py,sha256=qVgzHqxWNynWi27scszWv7VNMzfK31lxVkjWqcRLvT4,19255
pypdns/errors.py,sha256=4MxasDp-S91T9sUB6Yd5SqU5FiTpw6VlHqjgDZsoUNk,510
pypdns/py.typed,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
pypdns-2.2.2.dist-info/LICENSE,sha256=o1p6jKkqoo0k2KXZ23F8zTPaRGIoF8Gu9ADxi-QiUyo,1576
pypdns-2.2.2.dist-info/METADATA,sha256=Q0qZyPGncQznPp-dGsujZavBZXOvzluzczmhO5qBpAk,2758
pypdns-2.2.2.dist-info/WHEEL,sha256=FMvqSimYX_P7y0a7UY-_Mc83r5zkBZsCYPm7Lr0Bsq4,88
pypdns-2.2.2.dist-info/entry_points.txt,sha256=9MC-9q1FbTVA0TQgOgc4JMUz9comV4RsGdeDel5gdxg,36
pypdns-2.2.2.dist-info/RECORD,,
